name: Deploy Lambda Functions

on:
  push:
    branches:
      - main # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Match your Lambda runtime environment

      - name: Deploy get_meal
        run: |
          set -e
          cd get_meal
          pip install -r ../requirements.txt -t package
          cp get_meal.py package/
          cd package
          zip -r ../get_meal.zip .
          cd ..
          aws lambda update-function-code --function-name get_meal --zip-file fileb://get_meal.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"

      # Deploy Lambda Function 2
    #   - name: Deploy Lambda Function 2
    #     run: |
    #       cd lambda_function_2
    #       pip install -r requirements.txt
    #       # Zip your function code
    #       zip -r function_2.zip .
    #       aws lambda update-function-code --function-name function_2_name --zip-file fileb://function_2.zip
    #     env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       AWS_REGION: "your_aws_region"

    # Add similar steps for other Lambda functions
